---
#
# Ansible managed
#
repository:
  description: Install dependencies to support the Ansible core modules.
  homepage: https://robertdebock.nl/
  topics: coredependencies, system, ansible, molecule, playbook
